<<<<<<< HEAD
name: HW-3 CI
=======
name: HW-1 CI
>>>>>>> 37a6c20 (HW3Branch)

on:
  push:
    branches:
<<<<<<< HEAD
      - HW3

=======
      - hw3
>>>>>>> 37a6c20 (HW3Branch)
  pull_request:
    branches:
      - main

jobs:
  hw3-CI:

    runs-on: ubuntu-latest

  
    steps:

      - uses: actions/checkout@v3


      - name: Set up terraform
        uses: hashicorp/setup-terraform@v1


      - name: format check
        run: terraform fmt